# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  path_filters:
    - "!.agents/**"
    - "!.claude/**"
    - "!.cursor/**"
    - "!.github/skills/**"
    - "!src/__registry__/**"
    - "!public/**"
