// Thanks @shadcn for the inspiration and some code references in this file.

import { promises as fs } from "node:fs"
import path from "node:path"
import { rimraf } from "rimraf"
import { registrySchema, type Registry } from "shadcn/schema"

import { getAllBlocks } from "@/lib/blocks"

/**
 * build-registry.mts is the single registry pipeline.
 *
 * Source of truth:
 * - Authored raw component source lives in src/registry/components.
 * - Authored demo source lives in src/registry/examples.
 *
 * Persistent outputs:
 * - registry.json
 * - registry-stats.json
 * - src/registry/__index__.tsx
 * - public/r/*
 */

const REGISTRY_PATH = path.join(process.cwd(), "src/registry")

/**
 * Build registry.json, src/registry/__index__.tsx
 */
export async function buildRegistry(registry: Registry) {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import * as React from "react"

export const Index: Record<string, any> = {`
  for (const item of registry.items) {
    if (!Array.isArray(item.files) || !item.files?.length) {
      continue
    }

    const componentFilePath = item.files[0].path
    const componentPath = componentFilePath.startsWith("src/")
      ? componentFilePath.replace("src/", "@/")
      : `@/registry/${componentFilePath}`

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    files: [${item.files.map((file) => {
      const filePath = file.path.startsWith("src/")
        ? file.path
        : `src/registry/${file.path}`
      return `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}",
    }`
    })}],
    component: React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || "${item.name}"
      return { default: mod.default || mod[exportName] }
    }),
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`
  }

  index += `
}`

  // Build registry.json
  const publishedItems = registry.items.filter(
    (item) => item.type !== "registry:example"
  )

  const registryJSON = JSON.stringify(
    {
      $schema: "https://ui.shadcn.com/schema/registry.json",
      name: "ncdai",
      homepage: "https://chanhdai.com/components",
      items: publishedItems.map((item) => {
        return {
          ...item,
          author: item.author ?? "ncdai <dai@chanhdai.com>",
          files:
            item.files?.map((file) => {
              if (file.path.startsWith("src/")) {
                return file
              }

              return {
                ...file,
                path: `src/registry/${file.path}`,
              }
            }) ?? [],
        }
      }),
    },
    null,
    2
  )

  // Build registry.json
  console.log("📦 Building registry.json...")
  await rimraf(path.join(process.cwd(), "registry.json"))
  await fs.writeFile(
    path.join(process.cwd(), "registry.json"),
    registryJSON,
    "utf8"
  )

  // Build registry-stats.json — the counts alone, so consumers that need only
  // a number never import the whole registry.
  console.log("\n📦 Building registry-stats.json...")
  const countByType = publishedItems.reduce<Record<string, number>>(
    (counts, item) => {
      counts[item.type] = (counts[item.type] ?? 0) + 1
      return counts
    },
    {}
  )

  await fs.writeFile(
    path.join(process.cwd(), "registry-stats.json"),
    `${JSON.stringify({ total: publishedItems.length, countByType }, null, 2)}\n`,
    "utf8"
  )

  // Build src/registry/__index__.tsx
  console.log("\n📦 Building src/registry/__index__.tsx...")
  await rimraf(path.join(REGISTRY_PATH, "__index__.tsx"))
  await fs.writeFile(path.join(REGISTRY_PATH, "__index__.tsx"), index, "utf8")
}

async function buildBlocksIndex() {
  const blocks = await getAllBlocks(["registry:block"])

  const payload = blocks.map((block) => ({
    name: block.name,
    description: block.description,
    categories: block.categories,
  }))

  // Build src/registry/__blocks__.json
  await rimraf(path.join(REGISTRY_PATH, "__blocks__.json"))
  const blocksJsonPath = path.join(REGISTRY_PATH, "__blocks__.json")
  await fs.writeFile(blocksJsonPath, JSON.stringify(payload, null, 2))
}

try {
  const totalStart = performance.now()

  const { registry } = await import("@/registry/index")

  const result = registrySchema.safeParse(registry)

  if (!result.success) {
    console.error(result.error)
    process.exit(1)
  }

  await buildRegistry(result.data)

  console.log("\n🗂️ Building src/registry/__blocks__.json...")
  await buildBlocksIndex()

  const elapsed = ((performance.now() - totalStart) / 1000).toFixed(2)
  console.log(`\n✅ Build complete in ${elapsed}s!`)
} catch (error) {
  console.error(error)
  process.exit(1)
}
